name: 'feature_platform'
version: '1.0.0'
config-version: 2
profile: 'feature_platform'

model-paths: ["models"]
seed-paths: ["seeds"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  # Resolves to absolute path in Cosmos, relative path locally
  raw_data_path: "{{ env_var('RAW_DATA_PATH', 'var/data/yellow_tripdata_2026-05.parquet') }}"