warehouse:
  type: snowflake
  path: null
  schema: prod_dbt

feast:
  online_store_type: redis
  online_store_path: "redis.prod.internal:6379"
  materialize_start: "2026-01-01T00:00:00"
  materialize_end: "2026-09-01T00:00:00"

max_active_tasks: 128